# Generated by Django 5.2 on 2025-05-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zchat', '0003_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='topic',
        ),
    ]
