# Generated by Django 5.2 on 2025-05-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zchat', '0005_alter_room_options_room_patricipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='patricipants',
            new_name='participants',
        ),
    ]
